### ISSUE TITLE
Does ManifestWork support running cross clusters?

### ISSUE THREAD

**Issue by SparkSnail** [open-cluster-management-io/community#128]
Hi,
    I'm new to OCM, and I have run Placement and ManifestWork examples successfully. I have a question now, If I have selected 2 suitable clusters, how can I submit a ManifestWork to run a deployment on both 2 clusters? In official example, it only describe running on one specific cluster by setting namespace, how can I run one ManifestWork on both cluster1 and cluster2?
```
apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  name: hello-work
  namespace: cluster1
  labels:
    app: hello
```
