### ISSUE TITLE
No "IamPolicy" on Hub

### ISSUE THREAD

**Issue by xuezhaojun** [open-cluster-management-io/community#46]
What have I done:

Step1: [Install Policy framework](https://open-cluster-management.io/getting-started/integration/policy-framework/)

Step2: [Install Policy controllers](https://open-cluster-management.io/getting-started/integration/policy-controllers/)

Step3: Apply IamPolicy on OKD `kubectl apply -f policy-test/iam/policy-iam.yaml` and the yaml file is:

```
apiVersion: policy.open-cluster-management.io/v1
kind: IamPolicy
metadata:
  name: iam-grc-policy
  label:
    category: "System-Integrity"
spec:
  namespaceSelector:
    include: ["default","kube-*"]
    exclude: ["kube-system"]
  remediationAction: inform
  disabled: false
  maxClusterRoleBindingUsers: 5
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-iam
placementRef:
  name: placement-policy-iam
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: iam-grc-policy
    kind: IamPolicy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-iam
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions: []
```

Then I got an error:
```
error: unable to recognize "policy-test/iam/policy-iam.yaml": no matches for kind "IamPolicy" in version "policy.open-cluster-management.io/v1"
```
