### ISSUE TITLE
Create resource "Application" failed on OKD

### ISSUE THREAD

**Issue by xuezhaojun** [open-cluster-management-io/community#47]
What have I done:

Step1: [Install  from source](https://open-cluster-management.io/getting-started/integration/app-lifecycle/#install-from-source)

Step2: Run `kubectl apply -f application.yaml` and the yaml file is:
```
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: okd
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
```

Then I got an error:
```
Error "failed calling webhook "applications.apps.open-cluster-management.webhook": Post "https://multicluster-operators-application-svc.multicluster-operators.svc:443/app-validate?timeout=10s": no endpoints available for service "multicluster-operators-application-svc"" for field "undefined".
```
