### ISSUE TITLE
The risk of user token expired

### ISSUE THREAD

**Issue by xuezhaojun** [open-cluster-management-io/community#5]
In the installations of the Klusterlet and the subscription operators to managed cluster(s) we need to use the kubeconfig of Hub cluster to init a kubeclient. (the kubeconfig store as secret on a managed cluster)

But if we use "oc login" to access an OKD cluster, we only get kubeconfig like this:

```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://api.aws-okd.dev04.red-chesterfield.com:6443
  name: api-aws-okd-dev04-red-chesterfield-com:6443
contexts:
- context:
    cluster: api-aws-okd-dev04-red-chesterfield-com:6443
    namespace: default
    user: kube:admin/api-aws-okd-dev04-red-chesterfield-com:6443
  name: default/api-aws-okd-dev04-red-chesterfield-com:6443/kube:admin
current-context: default/api-aws-okd-dev04-red-chesterfield-com:6443/kube:admin
kind: Config
preferences: {}
users:
- name: kube:admin/api-aws-okd-dev04-red-chesterfield-com:6443
  user:
    token: sha256~<some token>
```

The token will expired after 24 hour. So if pods on a managed cluster restart after 24 hours, it can not connect to Hub anymore.
