### ISSUE TITLE
Manifestwork can not package kube job and distribute to managed cluster

### ISSUE THREAD

**Issue by zychina** [open-cluster-management-io/community#91]
1. Can create kube batch job in managedcluster
```
cat << EOF | k apply -f -
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  backoffLimit: 4
  parallelism: 2
  template:
    spec:
      containers:
      - name: pi1
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
EOF
job.batch/pi created
```
2. But I can not create manifestwork on hub cluster to distribute the job to managed cluster.
```
cat << EOF | k apply -f -
apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  name: job--pi
  namespace: managed-cluster1
spec:
  workload:
    manifests:
      - apiVersion: batch/v1
        kind: Job
        metadata:
          name: pi
        spec:
          backoffLimit: 4
          parallelism: 2
          template:
            spec:
              containers:
                - name: pi1
                  image: perl
                  command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
              restartPolicy: Never
EOF
manifestwork.work.open-cluster-management.io/job--pi created
```
k get manifestworks.work.open-cluster-management.io job--pi--226649030483297445 -n managed-cluster1 -o yaml
apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"work.open-cluster-management.io/v1","kind":"ManifestWork","metadata":{"annotations":{},"name":"job--pi","namespace":"managed-cluster1"},"spec":{"workload":{"manifests":[{"apiVersion":"batch/v1","kind":"Job","metadata":{"name":"pi"},"spec":{"backoffLimit":4,"parallelism":2,"template":{"spec":{"containers":[{"command":["perl","-Mbignum=bpi","-wle","print bpi(2000)"],"image":"perl","name":"pi1"}],"restartPolicy":"Never"}}}}]}}}
  creationTimestamp: "2021-09-29T08:22:16Z"
  finalizers:
  - cluster.open-cluster-management.io/manifest-work-cleanup
  generation: 1
  name: job--pi--226649030483297445
  namespace: managed-cluster1
  resourceVersion: "32927696"
  uid: 41dcee2e-d21d-448b-8323-654287c69510
spec:
  workload:
    manifests:
    - apiVersion: batch/v1
      kind: Job
      metadata:
        name: pi
      spec:
        backoffLimit: 4
        parallelism: 2
        template:
          spec:
            containers:
            - command:
              - perl
              - -Mbignum=bpi
              - -wle
              - print bpi(2000)
              image: perl
              name: pi1
            restartPolicy: Never
status:
  conditions:
  - lastTransitionTime: "2021-09-29T08:22:17Z"
    message: Failed to apply manifest work
    reason: AppliedManifestWorkFailed
    status: "False"
    type: Applied
  - lastTransitionTime: "2021-09-29T08:22:17Z"
    message: 1 of 1 resources are not available
    reason: ResourcesNotAvailable
    status: "False"
    type: Available
  resourceStatus:
    manifests:
    - conditions:
      - lastTransitionTime: "2021-09-29T08:22:17Z"
        message: 'Failed to apply manifest: the server does not allow this method
          on the requested resource'
        reason: AppliedManifestFailed
        status: "False"
        type: Applied
      - lastTransitionTime: "2021-09-29T08:22:17Z"
        message: Resource is not available
        reason: ResourceNotAvailable
        status: "False"
        type: Available
      resourceMeta:
        group: batch
        kind: Job
        name: pi
        namespace: ""
        ordinal: 0
        resource: jobs
        version: v1
```

The error is "Failed to apply manifest: the server does not allow this method on the requested resource"

Anyone have a try, thank you.
